### Register User
POST http://localhost:3000/api/users
Content-Type: application/json
Accept: application/json

{
  "username": "aditya",
  "password": "aditya",
  "name": "Aditya"
}

### Login User
POST http://localhost:3000/api/users/login
Content-Type: application/json
Accept: application/json

{
  "username": "aditya",
  "password": "aditya"
}

### Get User
GET http://localhost:3000/api/users/current
Content-Type: application/json
Accept: application/json
X-API-TOKEN: c390d47f-9ff4-4cbc-9a16-51ddb965269d

### Logout User
DELETE http://localhost:3000/api/users/current
Content-Type: application/json
Accept: application/json
X-API-TOKEN: c390d47f-9ff4-4cbc-9a16-51ddb965269d

### Update User
PATCH http://localhost:3000/api/users/current
Content-Type: application/json
Accept: application/json
X-API-TOKEN: c390d47f-9ff4-4cbc-9a16-51ddb965269d

{
  "name": "Aditya Ricki",
  "username": "aditya",
  "password": "aditya"
}

### Create Contact
POST http://localhost:3000/api/contacts
Content-Type: application/json
Accept: application/json
X-API-TOKEN: c390d47f-9ff4-4cbc-9a16-51ddb965269d

{
  "first_name": "Erni",
  "last_name": "Safitri",
  "email": "aditya@ricki.com",
  "phone": "089873168713"
}

### Update Contact
PUT http://localhost:3000/api/contacts/461
Content-Type: application/json
Accept: application/json
X-API-TOKEN: c390d47f-9ff4-4cbc-9a16-51ddb965269d

{
  "first_name": "Aditya",
  "last_name": "Ricki Julianto",
  "email": "aditya@ricki.com",
  "phone": "089873168713"
}

### Get Contact
GET http://localhost:3000/api/contacts/461
Accept: application/json
X-API-TOKEN: c390d47f-9ff4-4cbc-9a16-51ddb965269d

### Delete Contact
DELETE http://localhost:3000/api/contacts/461
Accept: application/json
X-API-TOKEN: c390d47f-9ff4-4cbc-9a16-51ddb965269d

### Search Contact
GET http://localhost:3000/api/contacts?size=1&page=1&name=a&email=a&phone=0
Accept: application/json
X-API-TOKEN: c390d47f-9ff4-4cbc-9a16-51ddb965269d

### Create Address
POST http://localhost:3000/api/contacts/462/addresses
Content-Type: application/json
Accept: application/json
X-API-TOKEN: c390d47f-9ff4-4cbc-9a16-51ddb965269d

{
  "street": "Jl. Sambirejo",
  "city": "Gunungkidul",
  "province": "DIY",
  "country": "Indonesia",
  "postal_code": "55853"
}

### Update Address
PUT http://localhost:3000/api/contacts/462/addresses/139
Content-Type: application/json
Accept: application/json
X-API-TOKEN: c390d47f-9ff4-4cbc-9a16-51ddb965269d

{
  "street": "Jl. Sambirejo",
  "city": "Gunungkidul",
  "province": "Yogyakarta",
  "country": "Indonesia",
  "postal_code": "55853"
}

### Get Address
GET http://localhost:3000/api/contacts/462/addresses/139
Accept: application/json
X-API-TOKEN: c390d47f-9ff4-4cbc-9a16-51ddb965269d

### Delete Address
DELETE http://localhost:3000/api/contacts/462/addresses/139
Accept: application/json
X-API-TOKEN: c390d47f-9ff4-4cbc-9a16-51ddb965269d

### List Address
GET http://localhost:3000/api/contacts/462/addresses
Accept: application/json
X-API-TOKEN: c390d47f-9ff4-4cbc-9a16-51ddb965269d
